/*
 * Generated by gdbus-codegen 2.40.0. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifndef __SRC_INTERFACES_HOSTNAMED_HOSTNAMED_GEN_H__
#define __SRC_INTERFACES_HOSTNAMED_HOSTNAMED_GEN_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.freedesktop.hostname1 */

#define HOSTNAMED_TYPE_HOSTNAME1 (hostnamed_hostname1_get_type ())
#define HOSTNAMED_HOSTNAME1(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HOSTNAMED_TYPE_HOSTNAME1, hostnamedHostname1))
#define HOSTNAMED_IS_HOSTNAME1(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HOSTNAMED_TYPE_HOSTNAME1))
#define HOSTNAMED_HOSTNAME1_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), HOSTNAMED_TYPE_HOSTNAME1, hostnamedHostname1Iface))

struct _hostnamedHostname1;
typedef struct _hostnamedHostname1 hostnamedHostname1;
typedef struct _hostnamedHostname1Iface hostnamedHostname1Iface;

struct _hostnamedHostname1Iface
{
  GTypeInterface parent_iface;


  gboolean (*handle_set_chassis) (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1);

  gboolean (*handle_set_hostname) (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1);

  gboolean (*handle_set_icon_name) (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1);

  gboolean (*handle_set_pretty_hostname) (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1);

  gboolean (*handle_set_static_hostname) (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1);

  const gchar * (*get_chassis) (hostnamedHostname1 *object);

  const gchar * (*get_hostname) (hostnamedHostname1 *object);

  const gchar * (*get_icon_name) (hostnamedHostname1 *object);

  const gchar * (*get_kernel_name) (hostnamedHostname1 *object);

  const gchar * (*get_kernel_release) (hostnamedHostname1 *object);

  const gchar * (*get_kernel_version) (hostnamedHostname1 *object);

  const gchar * (*get_operating_system_cpename) (hostnamedHostname1 *object);

  const gchar * (*get_operating_system_pretty_name) (hostnamedHostname1 *object);

  const gchar * (*get_pretty_hostname) (hostnamedHostname1 *object);

  const gchar * (*get_static_hostname) (hostnamedHostname1 *object);

};

GType hostnamed_hostname1_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *hostnamed_hostname1_interface_info (void);
guint hostnamed_hostname1_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void hostnamed_hostname1_complete_set_hostname (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation);

void hostnamed_hostname1_complete_set_static_hostname (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation);

void hostnamed_hostname1_complete_set_pretty_hostname (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation);

void hostnamed_hostname1_complete_set_icon_name (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation);

void hostnamed_hostname1_complete_set_chassis (
    hostnamedHostname1 *object,
    GDBusMethodInvocation *invocation);



/* D-Bus method calls: */
void hostnamed_hostname1_call_set_hostname (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hostnamed_hostname1_call_set_hostname_finish (
    hostnamedHostname1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean hostnamed_hostname1_call_set_hostname_sync (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);

void hostnamed_hostname1_call_set_static_hostname (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hostnamed_hostname1_call_set_static_hostname_finish (
    hostnamedHostname1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean hostnamed_hostname1_call_set_static_hostname_sync (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);

void hostnamed_hostname1_call_set_pretty_hostname (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hostnamed_hostname1_call_set_pretty_hostname_finish (
    hostnamedHostname1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean hostnamed_hostname1_call_set_pretty_hostname_sync (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);

void hostnamed_hostname1_call_set_icon_name (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hostnamed_hostname1_call_set_icon_name_finish (
    hostnamedHostname1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean hostnamed_hostname1_call_set_icon_name_sync (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);

void hostnamed_hostname1_call_set_chassis (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean hostnamed_hostname1_call_set_chassis_finish (
    hostnamedHostname1 *proxy,
    GAsyncResult *res,
    GError **error);

gboolean hostnamed_hostname1_call_set_chassis_sync (
    hostnamedHostname1 *proxy,
    const gchar *arg_unnamed_arg0,
    gboolean arg_unnamed_arg1,
    GCancellable *cancellable,
    GError **error);



/* D-Bus property accessors: */
const gchar *hostnamed_hostname1_get_hostname (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_hostname (hostnamedHostname1 *object);
void hostnamed_hostname1_set_hostname (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_static_hostname (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_static_hostname (hostnamedHostname1 *object);
void hostnamed_hostname1_set_static_hostname (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_pretty_hostname (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_pretty_hostname (hostnamedHostname1 *object);
void hostnamed_hostname1_set_pretty_hostname (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_icon_name (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_icon_name (hostnamedHostname1 *object);
void hostnamed_hostname1_set_icon_name (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_chassis (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_chassis (hostnamedHostname1 *object);
void hostnamed_hostname1_set_chassis (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_kernel_name (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_kernel_name (hostnamedHostname1 *object);
void hostnamed_hostname1_set_kernel_name (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_kernel_release (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_kernel_release (hostnamedHostname1 *object);
void hostnamed_hostname1_set_kernel_release (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_kernel_version (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_kernel_version (hostnamedHostname1 *object);
void hostnamed_hostname1_set_kernel_version (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_operating_system_pretty_name (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_operating_system_pretty_name (hostnamedHostname1 *object);
void hostnamed_hostname1_set_operating_system_pretty_name (hostnamedHostname1 *object, const gchar *value);

const gchar *hostnamed_hostname1_get_operating_system_cpename (hostnamedHostname1 *object);
gchar *hostnamed_hostname1_dup_operating_system_cpename (hostnamedHostname1 *object);
void hostnamed_hostname1_set_operating_system_cpename (hostnamedHostname1 *object, const gchar *value);


/* ---- */

#define HOSTNAMED_TYPE_HOSTNAME1_PROXY (hostnamed_hostname1_proxy_get_type ())
#define HOSTNAMED_HOSTNAME1_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HOSTNAMED_TYPE_HOSTNAME1_PROXY, hostnamedHostname1Proxy))
#define HOSTNAMED_HOSTNAME1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), HOSTNAMED_TYPE_HOSTNAME1_PROXY, hostnamedHostname1ProxyClass))
#define HOSTNAMED_HOSTNAME1_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), HOSTNAMED_TYPE_HOSTNAME1_PROXY, hostnamedHostname1ProxyClass))
#define HOSTNAMED_IS_HOSTNAME1_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HOSTNAMED_TYPE_HOSTNAME1_PROXY))
#define HOSTNAMED_IS_HOSTNAME1_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), HOSTNAMED_TYPE_HOSTNAME1_PROXY))

typedef struct _hostnamedHostname1Proxy hostnamedHostname1Proxy;
typedef struct _hostnamedHostname1ProxyClass hostnamedHostname1ProxyClass;
typedef struct _hostnamedHostname1ProxyPrivate hostnamedHostname1ProxyPrivate;

struct _hostnamedHostname1Proxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  hostnamedHostname1ProxyPrivate *priv;
};

struct _hostnamedHostname1ProxyClass
{
  GDBusProxyClass parent_class;
};

GType hostnamed_hostname1_proxy_get_type (void) G_GNUC_CONST;

void hostnamed_hostname1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
hostnamedHostname1 *hostnamed_hostname1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
hostnamedHostname1 *hostnamed_hostname1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void hostnamed_hostname1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
hostnamedHostname1 *hostnamed_hostname1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
hostnamedHostname1 *hostnamed_hostname1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define HOSTNAMED_TYPE_HOSTNAME1_SKELETON (hostnamed_hostname1_skeleton_get_type ())
#define HOSTNAMED_HOSTNAME1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HOSTNAMED_TYPE_HOSTNAME1_SKELETON, hostnamedHostname1Skeleton))
#define HOSTNAMED_HOSTNAME1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), HOSTNAMED_TYPE_HOSTNAME1_SKELETON, hostnamedHostname1SkeletonClass))
#define HOSTNAMED_HOSTNAME1_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), HOSTNAMED_TYPE_HOSTNAME1_SKELETON, hostnamedHostname1SkeletonClass))
#define HOSTNAMED_IS_HOSTNAME1_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HOSTNAMED_TYPE_HOSTNAME1_SKELETON))
#define HOSTNAMED_IS_HOSTNAME1_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), HOSTNAMED_TYPE_HOSTNAME1_SKELETON))

typedef struct _hostnamedHostname1Skeleton hostnamedHostname1Skeleton;
typedef struct _hostnamedHostname1SkeletonClass hostnamedHostname1SkeletonClass;
typedef struct _hostnamedHostname1SkeletonPrivate hostnamedHostname1SkeletonPrivate;

struct _hostnamedHostname1Skeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  hostnamedHostname1SkeletonPrivate *priv;
};

struct _hostnamedHostname1SkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType hostnamed_hostname1_skeleton_get_type (void) G_GNUC_CONST;

hostnamedHostname1 *hostnamed_hostname1_skeleton_new (void);


/* ---- */

#define HOSTNAMED_TYPE_OBJECT (hostnamed_object_get_type ())
#define HOSTNAMED_OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HOSTNAMED_TYPE_OBJECT, hostnamedObject))
#define HOSTNAMED_IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HOSTNAMED_TYPE_OBJECT))
#define HOSTNAMED_OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), HOSTNAMED_TYPE_OBJECT, hostnamedObject))

struct _hostnamedObject;
typedef struct _hostnamedObject hostnamedObject;
typedef struct _hostnamedObjectIface hostnamedObjectIface;

struct _hostnamedObjectIface
{
  GTypeInterface parent_iface;
};

GType hostnamed_object_get_type (void) G_GNUC_CONST;

hostnamedHostname1 *hostnamed_object_get_hostname1 (hostnamedObject *object);
hostnamedHostname1 *hostnamed_object_peek_hostname1 (hostnamedObject *object);

#define HOSTNAMED_TYPE_OBJECT_PROXY (hostnamed_object_proxy_get_type ())
#define HOSTNAMED_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HOSTNAMED_TYPE_OBJECT_PROXY, hostnamedObjectProxy))
#define HOSTNAMED_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), HOSTNAMED_TYPE_OBJECT_PROXY, hostnamedObjectProxyClass))
#define HOSTNAMED_OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), HOSTNAMED_TYPE_OBJECT_PROXY, hostnamedObjectProxyClass))
#define HOSTNAMED_IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HOSTNAMED_TYPE_OBJECT_PROXY))
#define HOSTNAMED_IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), HOSTNAMED_TYPE_OBJECT_PROXY))

typedef struct _hostnamedObjectProxy hostnamedObjectProxy;
typedef struct _hostnamedObjectProxyClass hostnamedObjectProxyClass;
typedef struct _hostnamedObjectProxyPrivate hostnamedObjectProxyPrivate;

struct _hostnamedObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  hostnamedObjectProxyPrivate *priv;
};

struct _hostnamedObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType hostnamed_object_proxy_get_type (void) G_GNUC_CONST;
hostnamedObjectProxy *hostnamed_object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define HOSTNAMED_TYPE_OBJECT_SKELETON (hostnamed_object_skeleton_get_type ())
#define HOSTNAMED_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HOSTNAMED_TYPE_OBJECT_SKELETON, hostnamedObjectSkeleton))
#define HOSTNAMED_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), HOSTNAMED_TYPE_OBJECT_SKELETON, hostnamedObjectSkeletonClass))
#define HOSTNAMED_OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), HOSTNAMED_TYPE_OBJECT_SKELETON, hostnamedObjectSkeletonClass))
#define HOSTNAMED_IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HOSTNAMED_TYPE_OBJECT_SKELETON))
#define HOSTNAMED_IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), HOSTNAMED_TYPE_OBJECT_SKELETON))

typedef struct _hostnamedObjectSkeleton hostnamedObjectSkeleton;
typedef struct _hostnamedObjectSkeletonClass hostnamedObjectSkeletonClass;
typedef struct _hostnamedObjectSkeletonPrivate hostnamedObjectSkeletonPrivate;

struct _hostnamedObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  hostnamedObjectSkeletonPrivate *priv;
};

struct _hostnamedObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType hostnamed_object_skeleton_get_type (void) G_GNUC_CONST;
hostnamedObjectSkeleton *hostnamed_object_skeleton_new (const gchar *object_path);
void hostnamed_object_skeleton_set_hostname1 (hostnamedObjectSkeleton *object, hostnamedHostname1 *interface_);

/* ---- */

#define HOSTNAMED_TYPE_OBJECT_MANAGER_CLIENT (hostnamed_object_manager_client_get_type ())
#define HOSTNAMED_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), HOSTNAMED_TYPE_OBJECT_MANAGER_CLIENT, hostnamedObjectManagerClient))
#define HOSTNAMED_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), HOSTNAMED_TYPE_OBJECT_MANAGER_CLIENT, hostnamedObjectManagerClientClass))
#define HOSTNAMED_OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), HOSTNAMED_TYPE_OBJECT_MANAGER_CLIENT, hostnamedObjectManagerClientClass))
#define HOSTNAMED_IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), HOSTNAMED_TYPE_OBJECT_MANAGER_CLIENT))
#define HOSTNAMED_IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), HOSTNAMED_TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _hostnamedObjectManagerClient hostnamedObjectManagerClient;
typedef struct _hostnamedObjectManagerClientClass hostnamedObjectManagerClientClass;
typedef struct _hostnamedObjectManagerClientPrivate hostnamedObjectManagerClientPrivate;

struct _hostnamedObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  hostnamedObjectManagerClientPrivate *priv;
};

struct _hostnamedObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

GType hostnamed_object_manager_client_get_type (void) G_GNUC_CONST;

GType hostnamed_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void hostnamed_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *hostnamed_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *hostnamed_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void hostnamed_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *hostnamed_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *hostnamed_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS

#endif /* __SRC_INTERFACES_HOSTNAMED_HOSTNAMED_GEN_H__ */
